### ISSUE TITLE
thunderbird 17 crash

### ISSUE THREAD

**Issue by dennyhalim** [kylehuff/webpg-firefox#13] opened 2013-07-26 04:22 UTC
thunderbird 17 on win7 crash after webpg installed.

**Comment by darkpixel** [comment] 2013-07-27 16:58
Can you provide a bit more detail?  Do you get an error message?  Have you tried removing webpg to see if the crash still occurs?  Have you tried disabling other plugins to see if it's a conflict between plugins?

**Comment by dennyhalim** [comment] 2013-07-30 11:42
didnt have time to try more..
all i tried is install webpg, tb crash. remove webpg, tb runs fine.

only have 2 other addons: lightning and google contact.

**Comment by darkpixel** [comment] 2013-07-30 19:08
I loaded thunderbird 17.0.7 under Windows 7 x64 along with the two plugins you mentioned and had no issues with crashing.  I'm closing the ticket as I can't reproduce it.

**Closed as completed by darkpixel** 2013-07-30 19:08 UTC
